import BlockType from '../types/BlockType';

export type BlockObject = {
    id: string; // 'y-x'
    blockType: BlockType;
}

const labyrinth: BlockObject[] = [
    { id: '0-0', blockType: BlockType.Wall }, { id: '0-1', blockType: BlockType.Wall }, { id: '0-2', blockType: BlockType.Wall }, { id: '0-3', blockType: BlockType.Wall }, { id: '0-4', blockType: BlockType.Wall }, { id: '0-5', blockType: BlockType.Wall }, { id: '0-6', blockType: BlockType.Wall }, { id: '0-7', blockType: BlockType.Wall }, { id: '0-8', blockType: BlockType.Wall }, { id: '0-9', blockType: BlockType.Wall }, { id: '0-10', blockType: BlockType.Wall }, { id: '0-11', blockType: BlockType.Wall }, { id: '0-12', blockType: BlockType.Wall }, { id: '0-13', blockType: BlockType.Wall }, { id: '0-14', blockType: BlockType.Wall }, { id: '0-15', blockType: BlockType.Wall },
    { id: '1-0', blockType: BlockType.Wall }, { id: '1-1', blockType: BlockType.Path }, { id: '1-2', blockType: BlockType.Path }, { id: '1-3', blockType: BlockType.Path }, { id: '1-4', blockType: BlockType.Wall }, { id: '1-5', blockType: BlockType.Path }, { id: '1-6', blockType: BlockType.Path }, { id: '1-7', blockType: BlockType.Path }, { id: '1-8', blockType: BlockType.Path }, { id: '1-9', blockType: BlockType.Path }, { id: '1-10', blockType: BlockType.Path }, { id: '1-11', blockType: BlockType.Path }, { id: '1-12', blockType: BlockType.Wall }, { id: '1-13', blockType: BlockType.Wall }, { id: '1-14', blockType: BlockType.Wall }, { id: '1-15', blockType: BlockType.Wall },
    { id: '2-0', blockType: BlockType.Wall }, { id: '2-1', blockType: BlockType.Wall }, { id: '2-2', blockType: BlockType.Wall }, { id: '2-3', blockType: BlockType.Path }, { id: '2-4', blockType: BlockType.Wall }, { id: '2-5', blockType: BlockType.Wall }, { id: '2-6', blockType: BlockType.Wall }, { id: '2-7', blockType: BlockType.Wall }, { id: '2-8', blockType: BlockType.Wall }, { id: '2-9', blockType: BlockType.Path }, { id: '2-10', blockType: BlockType.Wall }, { id: '2-11', blockType: BlockType.Path }, { id: '2-12', blockType: BlockType.Path }, { id: '2-13', blockType: BlockType.Path }, { id: '2-14', blockType: BlockType.Path }, { id: '2-15', blockType: BlockType.Wall },
    { id: '3-0', blockType: BlockType.Wall }, { id: '3-1', blockType: BlockType.Path }, { id: '3-2', blockType: BlockType.Wall }, { id: '3-3', blockType: BlockType.Path }, { id: '3-4', blockType: BlockType.Path }, { id: '3-5', blockType: BlockType.Path }, { id: '3-6', blockType: BlockType.Path }, { id: '3-7', blockType: BlockType.Path }, { id: '3-8', blockType: BlockType.Path }, { id: '3-9', blockType: BlockType.Path }, { id: '3-10', blockType: BlockType.Path }, { id: '3-11', blockType: BlockType.Path }, { id: '3-12', blockType: BlockType.Path }, { id: '3-13', blockType: BlockType.Path }, { id: '3-14', blockType: BlockType.Path }, { id: '3-15', blockType: BlockType.Wall },
    { id: '4-0', blockType: BlockType.Wall }, { id: '4-1', blockType: BlockType.Path }, { id: '4-2', blockType: BlockType.Path }, { id: '4-3', blockType: BlockType.Path }, { id: '4-4', blockType: BlockType.Wall }, { id: '4-5', blockType: BlockType.Wall }, { id: '4-6', blockType: BlockType.Wall }, { id: '4-7', blockType: BlockType.Wall }, { id: '4-8', blockType: BlockType.Path }, { id: '4-9', blockType: BlockType.Wall }, { id: '4-10', blockType: BlockType.Path }, { id: '4-11', blockType: BlockType.Path }, { id: '4-12', blockType: BlockType.Path }, { id: '4-13', blockType: BlockType.Wall }, { id: '4-14', blockType: BlockType.Path }, { id: '4-15', blockType: BlockType.Wall },
    { id: '5-0', blockType: BlockType.Wall }, { id: '5-1', blockType: BlockType.Path }, { id: '5-2', blockType: BlockType.Wall }, { id: '5-3', blockType: BlockType.Wall }, { id: '5-4', blockType: BlockType.Wall }, { id: '5-5', blockType: BlockType.Wall }, { id: '5-6', blockType: BlockType.Wall }, { id: '5-7', blockType: BlockType.Wall }, { id: '5-8', blockType: BlockType.Path }, { id: '5-9', blockType: BlockType.Wall }, { id: '5-10', blockType: BlockType.Path }, { id: '5-11', blockType: BlockType.Wall }, { id: '5-12', blockType: BlockType.Path }, { id: '5-13', blockType: BlockType.Wall }, { id: '5-14', blockType: BlockType.Path }, { id: '5-15', blockType: BlockType.Wall },
    { id: '6-0', blockType: BlockType.Wall }, { id: '6-1', blockType: BlockType.Path }, { id: '6-2', blockType: BlockType.Path }, { id: '6-3', blockType: BlockType.Path }, { id: '6-4', blockType: BlockType.Wall }, { id: '6-5', blockType: BlockType.Path }, { id: '6-6', blockType: BlockType.Wall }, { id: '6-7', blockType: BlockType.Wall }, { id: '6-8', blockType: BlockType.Path }, { id: '6-9', blockType: BlockType.Wall }, { id: '6-10', blockType: BlockType.Path }, { id: '6-11', blockType: BlockType.Wall }, { id: '6-12', blockType: BlockType.Path }, { id: '6-13', blockType: BlockType.Wall }, { id: '6-14', blockType: BlockType.Path }, { id: '6-15', blockType: BlockType.Wall },
    { id: '7-0', blockType: BlockType.Wall }, { id: '7-1', blockType: BlockType.Path }, { id: '7-2', blockType: BlockType.Path }, { id: '7-3', blockType: BlockType.Path }, { id: '7-4', blockType: BlockType.Wall }, { id: '7-5', blockType: BlockType.Path }, { id: '7-6', blockType: BlockType.Path }, { id: '7-7', blockType: BlockType.Path }, { id: '7-8', blockType: BlockType.Path }, { id: '7-9', blockType: BlockType.Path }, { id: '7-10', blockType: BlockType.Path }, { id: '7-11', blockType: BlockType.Path }, { id: '7-12', blockType: BlockType.Path }, { id: '7-13', blockType: BlockType.Path }, { id: '7-14', blockType: BlockType.Path }, { id: '7-15', blockType: BlockType.Wall },
    { id: '8-0', blockType: BlockType.Wall }, { id: '8-1', blockType: BlockType.Path }, { id: '8-2', blockType: BlockType.Wall }, { id: '8-3', blockType: BlockType.Wall }, { id: '8-4', blockType: BlockType.Wall }, { id: '8-5', blockType: BlockType.Wall }, { id: '8-6', blockType: BlockType.Wall }, { id: '8-7', blockType: BlockType.Wall }, { id: '8-8', blockType: BlockType.Wall }, { id: '8-9', blockType: BlockType.Wall }, { id: '8-10', blockType: BlockType.Wall }, { id: '8-11', blockType: BlockType.Wall }, { id: '8-12', blockType: BlockType.Path }, { id: '8-13', blockType: BlockType.Wall }, { id: '8-14', blockType: BlockType.Path }, { id: '8-15', blockType: BlockType.Wall },
    { id: '9-0', blockType: BlockType.Wall }, { id: '9-1', blockType: BlockType.Path }, { id: '9-2', blockType: BlockType.Wall }, { id: '9-3', blockType: BlockType.Path }, { id: '9-4', blockType: BlockType.Path }, { id: '9-5', blockType: BlockType.Path }, { id: '9-6', blockType: BlockType.Path }, { id: '9-7', blockType: BlockType.Path }, { id: '9-8', blockType: BlockType.Path }, { id: '9-9', blockType: BlockType.Wall }, { id: '9-10', blockType: BlockType.Path }, { id: '9-11', blockType: BlockType.Path }, { id: '9-12', blockType: BlockType.Path }, { id: '9-13', blockType: BlockType.Wall }, { id: '9-14', blockType: BlockType.Path }, { id: '9-15', blockType: BlockType.Wall },
    { id: '10-0', blockType: BlockType.Wall }, { id: '10-1', blockType: BlockType.Path }, { id: '10-2', blockType: BlockType.Wall }, { id: '10-3', blockType: BlockType.Path }, { id: '10-4', blockType: BlockType.Wall }, { id: '10-5', blockType: BlockType.Wall }, { id: '10-6', blockType: BlockType.Wall }, { id: '10-7', blockType: BlockType.Wall }, { id: '10-8', blockType: BlockType.Path }, { id: '10-9', blockType: BlockType.Wall }, { id: '10-10', blockType: BlockType.Wall }, { id: '10-11', blockType: BlockType.Wall }, { id: '10-12', blockType: BlockType.Wall }, { id: '10-13', blockType: BlockType.Wall }, { id: '10-14', blockType: BlockType.Path }, { id: '10-15', blockType: BlockType.Wall },
    { id: '11-0', blockType: BlockType.Wall }, { id: '11-1', blockType: BlockType.Path }, { id: '11-2', blockType: BlockType.Path }, { id: '11-3', blockType: BlockType.Path }, { id: '11-4', blockType: BlockType.Wall }, { id: '11-5', blockType: BlockType.Path }, { id: '11-6', blockType: BlockType.Path }, { id: '11-7', blockType: BlockType.Path }, { id: '11-8', blockType: BlockType.Path }, { id: '11-9', blockType: BlockType.Path }, { id: '11-10', blockType: BlockType.Path }, { id: '11-11', blockType: BlockType.Path }, { id: '11-12', blockType: BlockType.Path }, { id: '11-13', blockType: BlockType.Path }, { id: '11-14', blockType: BlockType.Path }, { id: '11-15', blockType: BlockType.Wall },
    { id: '12-0', blockType: BlockType.Wall }, { id: '12-1', blockType: BlockType.Wall }, { id: '12-2', blockType: BlockType.Wall }, { id: '12-3', blockType: BlockType.Wall }, { id: '12-4', blockType: BlockType.Wall }, { id: '12-5', blockType: BlockType.Path }, { id: '12-6', blockType: BlockType.Wall }, { id: '12-7', blockType: BlockType.Wall }, { id: '12-8', blockType: BlockType.Wall }, { id: '12-9', blockType: BlockType.Wall }, { id: '12-10', blockType: BlockType.Wall }, { id: '12-11', blockType: BlockType.Path }, { id: '12-12', blockType: BlockType.Wall }, { id: '12-13', blockType: BlockType.Wall }, { id: '12-14', blockType: BlockType.Wall }, { id: '12-15', blockType: BlockType.Wall },
    { id: '13-0', blockType: BlockType.Wall }, { id: '13-1', blockType: BlockType.Path }, { id: '13-2', blockType: BlockType.Path }, { id: '13-3', blockType: BlockType.Path }, { id: '13-4', blockType: BlockType.Wall }, { id: '13-5', blockType: BlockType.Path }, { id: '13-6', blockType: BlockType.Path }, { id: '13-7', blockType: BlockType.Path }, { id: '13-8', blockType: BlockType.Path }, { id: '13-9', blockType: BlockType.Path }, { id: '13-10', blockType: BlockType.Path }, { id: '13-11', blockType: BlockType.Path }, { id: '13-12', blockType: BlockType.Path }, { id: '13-13', blockType: BlockType.Path }, { id: '13-14', blockType: BlockType.Path }, { id: '13-15', blockType: BlockType.Wall },
    { id: '14-0', blockType: BlockType.Wall }, { id: '14-1', blockType: BlockType.Wall }, { id: '14-2', blockType: BlockType.Wall }, { id: '14-3', blockType: BlockType.Path }, { id: '14-4', blockType: BlockType.Path }, { id: '14-5', blockType: BlockType.Path }, { id: '14-6', blockType: BlockType.Path }, { id: '14-7', blockType: BlockType.Path }, { id: '14-8', blockType: BlockType.Path }, { id: '14-9', blockType: BlockType.Wall }, { id: '14-10', blockType: BlockType.Wall }, { id: '14-11', blockType: BlockType.Wall }, { id: '14-12', blockType: BlockType.Wall }, { id: '14-13', blockType: BlockType.Wall }, { id: '14-14', blockType: BlockType.Wall }, { id: '14-15', blockType: BlockType.Wall },
    { id: '15-0', blockType: BlockType.Wall }, { id: '15-1', blockType: BlockType.Wall }, { id: '15-2', blockType: BlockType.Wall }, { id: '15-3', blockType: BlockType.Wall }, { id: '15-4', blockType: BlockType.Wall }, { id: '15-5', blockType: BlockType.Wall }, { id: '15-6', blockType: BlockType.Wall }, { id: '15-7', blockType: BlockType.Wall }, { id: '15-8', blockType: BlockType.Wall }, { id: '15-9', blockType: BlockType.Wall }, { id: '15-10', blockType: BlockType.Wall }, { id: '15-11', blockType: BlockType.Wall }, { id: '15-12', blockType: BlockType.Wall }, { id: '15-13', blockType: BlockType.Wall }, { id: '15-14', blockType: BlockType.Wall }, { id: '15-15', blockType: BlockType.Wall },
];


export default labyrinth;